version: '2.0'

services:
  postgres:
    container_name: ecs_postgres
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
  app:
    container_name: ecs_app
    build: ./app
    command: rails server
    ports:
      - 3000:3000
    volumes:
      - ./app/:/app/
    links:
      - postgres
    depends_on:
      - postgres
