default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: postgres
  username: postgres
  password: senha123

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
